name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check if beta release
        id: check-beta
        run: |
          if [[ ${{ github.ref }} == *"beta"* ]]; then
            echo "is_beta=true" >> $GITHUB_OUTPUT
            echo "EP_PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "is_beta=false" >> $GITHUB_OUTPUT
            echo "EP_PRE_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Build application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Distribution
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: ${{ env.EP_PRE_RELEASE }}

      # Speichere die Builds als Artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            release/**/*.exe
            release/**/*.zip
            release/**/*.yml
            release/**/*.blockmap

  # Diese Job läuft nur, wenn der GitHub Release von electron-builder fehlschlägt
  fallback-release:
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: List downloaded artifacts
        run: |
          echo "Listing downloaded artifacts:"
          find . -type f | sort
        
      - name: Check if beta release
        id: check-beta
        run: |
          if [[ ${{ github.ref }} == *"beta"* ]]; then
            echo "is_beta=true" >> $GITHUB_OUTPUT
          else
            echo "is_beta=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release as fallback
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.exe
            **/*.zip
            **/*.yml
            **/*.blockmap
          draft: false
          prerelease: ${{ steps.check-beta.outputs.is_beta }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 